import Link from "next/link";

export default function termsofservice(){

    return (
    
        <div className="flex flex-col h-screen bg-[#2e1065]">
          <div className="sticky top-0 w-full p-4 bg-white overflow-hidden shadow-xl">
            <h1 className="text-xl text-left font-extrabold font-leading-none tracking-tight text-gray-900 md:text-xl lg:text-2xl dark:text-[#2e1065]">
              <Link href="/">WE.AI</Link>
            </h1>
          </div>
          <div className="flex flex-col h-screen p-4 overflow-auto">
            <h1 className="font-bold">Terms of Service</h1>
            <p>Effective Date: Dec 1st 2024</p>
            <p className="mt-5 text-justify">
              Welcome to the Western AI Assistant, a chatbot designed specifically for Western University engineering students. By accessing or using this service, you agree to the following Terms of Service. If you do not agree, please refrain from using the chatbot.
              The Western AI Assistant is a tool intended to assist with academic inquiries, course-related questions, and general guidance related to the engineering program at Western University. It is powered by artificial intelligence and may integrate with university resources to provide tailored support. By using the chatbot, you confirm that you are at least 18 years old or have parental consent to use the service.
              You agree to use the chatbot only for academic and professional purposes that align with Western University policies. Sharing sensitive, illegal, or inappropriate content through the chatbot is strictly prohibited. Misuse of the service, including any actions that violate university rules or applicable laws, may result in termination of access.
              The Western AI Assistant, including its content, design, and functionality, is the intellectual property of Western University or its licensors. Reproducing, distributing, or modifying any part of the service without prior authorization is not permitted.
              This service is provided "as-is" without any guarantees or warranties. While we strive for accuracy, responses generated by the chatbot may be incorrect or incomplete. Western University disclaims any responsibility for damages arising from the use of this service.
              Western University reserves the right to modify these Terms of Service at any time. Updates will be communicated through the chatbot or university communication channels. Continued use of the service following changes to the terms indicates your acceptance of the updated terms.
              If you violate these Terms of Service, Western University may suspend or terminate your access to the chatbot without prior notice.
            </p>
            <h1 className="font-bold mt-5">Privacy Policy</h1>
            <p>Effective Date: Dec 1st 2024</p>
            <p className="mt-5 text-justify">
              Your privacy is important to us. This Privacy Policy outlines how the Western AI Assistant collects, uses, and protects your information.
              We collect certain information to provide and improve the chatbot service. This includes your email address and user profile for authentication and usage tracking. We also collect logs of your interactions with the chatbot, such as the questions you ask and the responses you receive, to enhance the service.
              Your information is used to personalize responses, analyze trends, and ensure the chatbot's performance aligns with university policies. Usage data also helps us prevent misuse and improve the overall functionality of the service.
              We do not share your information with third parties, except when required by law, university policy, or when working with trusted service providers who maintain and improve the chatbot. Your data will never be sold or shared for marketing purposes.
              We use industry-standard security measures to protect your data from unauthorized access or disclosure. However, no system can guarantee absolute security. If a breach occurs, we will take all appropriate steps to address it promptly.
              Usage data is retained for a limited time to improve the chatbot's functionality, while personal information is stored only as long as necessary for its intended purposes or as required by law.
              You have the right to access, modify, or delete your personal data. To exercise these rights, please contact Western University IT Support. You may also opt out of using the chatbot at any time.
              This Privacy Policy may be updated periodically to reflect changes in the chatbot's functionality or data practices. Updates will be communicated through the chatbot or university communication channels.
              If you have questions or concerns about this Privacy Policy, please reach out to Western University IT Support.
              By using the Western AI Assistant, you acknowledge that you have read, understood, and agreed to this Privacy Policy.
            </p>
          </div>
          <div className="flex justify-left top-0 w-full p-4 bg-[#180738] overflow-hidden">
            <p className="text-md text-left mr-4 font-regular font-leading-none tracking-tight text-gray-900 md:text-md lg:lg dark:text-[#ffffff]">
              <Link href="/feedback">Feedback</Link>
            </p>
            <p className="text-md text-left font-regular font-leading-none tracking-tight text-gray-900 md:text-md lg:lg dark:text-[#ffffff]">
              <Link href="/termsofservice">Terms of Service</Link>
            </p>
          </div>
        </div>
      );

}