import { NextConfig, Metadata } from 'next';

const nextConfig: NextConfig = {
  /* config options here */
};

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default nextConfig;
